name: Terraform CI/CD
on: 
    # workflow_dispatch:
  push:
    branches:
      - main    # run only on main branch pushes

jobs:
  terraform:
    name: Terraform Workflow
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    
    steps:
      # Step 1: Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Step 2: Configure AWS credentials (LOGIN TO AWS)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Upload tfplan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan